### ISSUE TITLE
ABOUT PGPR baseline

### ISSUE THREAD

**Issue by Zxy0207** [giacoballoccu/explanation-quality-recsys#2]
When executing the adapted PGPR baseline, I had some problems;
I tried to use python main.py --dataset=ml1m --opt=soft --metrics=LIR/s_to_opt. and some other changes . However, they were all wrong
The wrong wae showen as follows:
main.py [-h] [--dataset DATASET] [--agent_topk AGENT_TOPK] [--opt OPT] [--alpha ALPHA] [--eval_baseline EVAL_BASELINE] [--log_enabled LOG_ENABLED] [--save_baseline_rec_quality_avgs SAVE_BASELINE_REC_QUALITY_AVGS]
               [--save_baseline_exp_quality_avgs SAVE_BASELINE_EXP_QUALITY_AVGS] [--save_baseline_rec_quality_distributions SAVE_BASELINE_REC_QUALITY_DISTRIBUTIONS]
               [--save_baseline_exp_quality_distributions SAVE_BASELINE_EXP_QUALITY_DISTRIBUTIONS] [--save_after_rec_quality_avgs SAVE_AFTER_REC_QUALITY_AVGS] [--save_after_exp_quality_avgs SAVE_AFTER_EXP_QUALITY_AVGS]
               [--save_after_rec_quality_distributions SAVE_AFTER_REC_QUALITY_DISTRIBUTIONS] [--save_after_exp_quality_distributions SAVE_AFTER_EXP_QUALITY_DISTRIBUTIONS] [--save_overall SAVE_OVERALL]
main.py: error: unrecognized arguments: --metrics=SEP/s_to_opt

**Comment by giacoballoccu** [comment]
As the error says ```main.py: error: unrecognized arguments: --metrics=SEP/s_to_opt```

The argument ```SEP/s_to_opt``` for the parameter ```--metrics``` is not supported. If you would like to optimize for SEP using the soft optimization you should specify when running ```--opt=soft --metrics=SEP```

**Comment by giacoballoccu** [comment]
I just noticed the readme wasn't updated with the latest changes, I updated it according to the current parameters

**Comment by Zxy0207** [comment]
Thank you very much. The problem has been solved
