### ISSUE TITLE
The chosen optimization doesn't exist...

### ISSUE THREAD

**Issue by Pursuerwener** [giacoballoccu/explanation-quality-recsys#3]
run

python main.py --dataset=ml1m --opt=soft--metrics=LIR

i get this problem

The chosen optimization doesn't exist...

**Comment by giacoballoccu** [comment]
You are quite right! I changed some parameters in the previous updates, from main.py you can see that the argument opt has as:     

```parser.add_argument('--opt', type=str, default="LIRopt", help='One of ["softETD", "softSEP", "softLIR", "ETDopt", "SEPopt", "LIRopt", "ETD_SEP_opt", "ETD_LIR_opt", "SEP_LIR_opt", "ETD_SEP_LIR_opt"]')```

The parameter metrics do not exist anymore and are merged into opt. So in your case, you should specify ```--opt=softLIR```

Let me know if this fixes your issue

I also updated the readme accordingly

**Comment by Pursuerwener** [comment]
thanks
